name: 'telegram_x_dart'
description: 'Telegram X Unofficial Port To Flutter With Telegram Client Tdlib Based Ultra FAST'
version: '0.0.0'
homepage: 'https://github.com/azkadev/telegram_x'
repository: 'https://github.com/azkadev/telegram_x'
issue_tracker: 'https://github.com/azkadev/telegram_x/issues'
documentation: 'https://github.com/azkadev/telegram_x/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dependencies: 
  path: '^1.9.0'
  universal_io: '^2.2.2' 
  mason_logger: '^0.2.5'
  collection: '^1.18.0'
  yaml: '^3.1.2'
  yaml_writer: '^2.0.0'
  general_lib: '^0.0.37'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
executables: 
  telegram_x_dart: 'telegram_x_dart'
