name: 'telegram_x_flutter'
description: 'Telegram X Unofficial Port To Flutter With Telegram Client Tdlib Based Ultra FAST'
version: '0.0.0'
homepage: 'https://github.com/azkadev/telegram_x'
repository: 'https://github.com/azkadev/telegram_x'
issue_tracker: 'https://github.com/azkadev/telegram_x/issues'
documentation: 'https://github.com/azkadev/telegram_x/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  general_lib: '^0.0.37'
  general_lib_flutter: '^0.0.20'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  # telegram_x: '^0.0.0'
  # telegram_x_dart: '^0.0.0'
  # telegram_x_scheme: '^0.0.0'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: null
