name: 'telegram_x_isar_scheme'
description: 'Telegram X Unofficial Port To Flutter With Telegram Client Tdlib Based Ultra FAST'
version: '0.0.0'
environment: 
  sdk: '^3.3.0'
dependencies: null
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
repository: 'https://github.com/azkadev/telegram_x'
homepage: 'https://github.com/azkadev/telegram_x'
issue_tracker: 'https://github.com/azkadev/telegram_x/issues'
documentation: 'https://github.com/azkadev/telegram_x/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
