name: 'telegram_x_scheme'
description: 'A sample command-line application.'
version: '0.0.0'
repository: 'https://github.com/azkadev/telegram_x'
homepage: 'https://github.com/azkadev/telegram_x'
issue_tracker: 'https://github.com/azkadev/telegram_x/issues'
documentation: 'https://github.com/azkadev/telegram_x/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.3.0'
dependencies: 
  path: '^1.9.0'
  general_lib: '^0.0.36'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
